services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Dvc\ContaoTemplateSupportBundle\:
    resource: ../../
    exclude:
      - '../../{DependencyInjection,Resources}'
